import type { NextPage } from "next";

import Head from "next/head";
import { useState } from "react";

import PokemonList from "../components/PokemonList";

const Home: NextPage = () => {
    const [pokemonSelected, setPokemonSelected] = useState(0);
    const [pokemonOffset, setPokemonOffset] = useState(0);

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex min-h-screen flex-row items-center justify-center bg-background relative bg-cover bg-no-repeat bg-center overflow-hidden">
                {/* <Frame currentPokemon={pokemonSelected} /> */}
                <PokemonList />
            </main>
        </>
    );
};

export default Home;

